cc_library(
        name = "knapsackwithconflicts",
        hdrs = ["knapsackwithconflicts.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "multidimensionalmultiplechoiceknapsack",
        hdrs = ["multidimensionalmultiplechoiceknapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "quadraticassignment",
        hdrs = ["quadraticassignment.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "cuttingstock",
        hdrs = ["cuttingstock.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "multipleknapsack",
        hdrs = ["multipleknapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "quadraticmultipleknapsack",
        hdrs = ["quadraticmultipleknapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "generalizedquadraticmultipleknapsack",
        hdrs = ["generalizedquadraticmultipleknapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "binpackingwithconflicts",
        hdrs = ["binpackingwithconflicts.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "travelingsalesman",
        hdrs = ["travelingsalesman.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "sequentialordering",
        hdrs = ["sequentialordering.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "travelingsalesmanwithreleasedates",
        hdrs = ["travelingsalesmanwithreleasedates.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "travelingrepairman",
        hdrs = ["travelingrepairman.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "timedependentorienteering",
        hdrs = ["timedependentorienteering.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
                "@boost//:filesystem",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "thieforienteering",
        hdrs = ["thieforienteering.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "capacitatedvehiclerouting",
        hdrs = ["capacitatedvehiclerouting.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "vehicleroutingwithtimewindows",
        hdrs = ["vehicleroutingwithtimewindows.hpp"],
        deps = [
                "@pugixml//:pugixml",
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "capacitatedopenvehiclerouting",
        hdrs = ["capacitatedopenvehiclerouting.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "schedulingwithsdsttwt",
        hdrs = ["schedulingwithsdsttwt.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "orderacceptanceandscheduling",
        hdrs = ["orderacceptanceandscheduling.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "batchschedulingtotalcompletiontime",
        hdrs = ["batchschedulingtotalcompletiontime.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "batchschedulingtotalweightedtardiness",
        hdrs = ["batchschedulingtotalweightedtardiness.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "parallelschedulingwithfamilysetuptimestwct",
        hdrs = ["parallelschedulingwithfamilysetuptimestwct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "starobservationscheduling",
        hdrs = ["starobservationscheduling.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutationflowshopschedulingmakespan",
        hdrs = ["permutationflowshopschedulingmakespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutationflowshopschedulingtct",
        hdrs = ["permutationflowshopschedulingtct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutationflowshopschedulingtt",
        hdrs = ["permutationflowshopschedulingtt.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "distributedpfssmakespan",
        hdrs = ["distributedpfssmakespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "distributedpfsstct",
        hdrs = ["distributedpfsstct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "nowaitjobshopschedulingmakespan",
        hdrs = ["nowaitjobshopschedulingmakespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
                "@interval-tree//:interval-tree",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "simpleassemblylinebalancing1",
        hdrs = ["simpleassemblylinebalancing1.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "ushapedassemblylinebalancing1",
        hdrs = ["ushapedassemblylinebalancing1.hpp"],
        deps = [
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "roadef2020",
        hdrs = ["roadef2020.hpp"],
        srcs = ["roadef2020.cpp"],
        deps = [
                "@simdjson//:simdjson",
                "@optimizationtools//optimizationtools:indexed_collections",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "checker",
        srcs = ["checker.cpp"],
        deps = [
                ":knapsackwithconflicts",
                ":multidimensionalmultiplechoiceknapsack",
                ":quadraticassignment",
                ":cuttingstock",
                ":multipleknapsack",
                ":quadraticmultipleknapsack",
                ":generalizedquadraticmultipleknapsack",
                ":binpackingwithconflicts",

                ":travelingsalesman",
                ":sequentialordering",
                ":travelingsalesmanwithreleasedates",
                ":travelingrepairman",
                ":timedependentorienteering",
                ":thieforienteering",
                ":capacitatedvehiclerouting",
                ":vehicleroutingwithtimewindows",
                ":capacitatedopenvehiclerouting",

                ":schedulingwithsdsttwt",
                ":orderacceptanceandscheduling",
                ":batchschedulingtotalcompletiontime",
                ":batchschedulingtotalweightedtardiness",
                ":parallelschedulingwithfamilysetuptimestwct",
                ":starobservationscheduling",
                ":permutationflowshopschedulingmakespan",
                ":permutationflowshopschedulingtct",
                ":permutationflowshopschedulingtt",
                ":distributedpfssmakespan",
                ":distributedpfsstct",
                ":nowaitjobshopschedulingmakespan",
                ":simpleassemblylinebalancing1",
                ":ushapedassemblylinebalancing1",
                ":roadef2020",

                "@boost//:program_options",
        ],
        copts = ["-std=c++14"],
        linkopts = ["-std=c++14"],
)

