cc_library(
        name = "knapsack_with_conflicts",
        hdrs = ["packing/knapsack_with_conflicts.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "multidimensional_multiple_choice_knapsack",
        hdrs = ["packing/multidimensional_multiple_choice_knapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "cutting_stock",
        hdrs = ["packing/cutting_stock.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "multiple_knapsack",
        hdrs = ["packing/multiple_knapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "quadratic_multiple_knapsack",
        hdrs = ["packing/quadratic_multiple_knapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "generalized_quadratic_multiple_knapsack",
        hdrs = ["packing/generalized_quadratic_multiple_knapsack.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "bin_packing_with_conflicts",
        hdrs = ["packing/bin_packing_with_conflicts.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)


cc_library(
        name = "quadratic_assignment",
        hdrs = ["assignment/quadratic_assignment.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)


cc_library(
        name = "traveling_salesman_with_release_dates",
        hdrs = ["routing/traveling_salesman_with_release_dates.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "traveling_repairman",
        hdrs = ["routing/traveling_repairman.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "time_dependent_orienteering",
        hdrs = ["routing/time_dependent_orienteering.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
                "@boost//:filesystem",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "orienteering_with_hotel_selection",
        hdrs = ["routing/orienteering_with_hotel_selection.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "capacitated_vehicle_routing",
        hdrs = ["routing/capacitated_vehicle_routing.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "vehicle_routing_with_time_windows",
        hdrs = ["routing/vehicle_routing_with_time_windows.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "capacitated_open_vehicle_routing",
        hdrs = ["routing/capacitated_open_vehicle_routing.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)


cc_library(
        name = "sequential_ordering",
        hdrs = ["scheduling/sequential_ordering.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "scheduling_with_sdst_twt",
        hdrs = ["scheduling/scheduling_with_sdst_twt.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "order_acceptance_and_scheduling",
        hdrs = ["scheduling/order_acceptance_and_scheduling.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "batch_scheduling_total_completion_time",
        hdrs = ["scheduling/batch_scheduling_total_completion_time.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "batch_scheduling_total_weighted_tardiness",
        hdrs = ["scheduling/batch_scheduling_total_weighted_tardiness.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "parallel_scheduling_with_family_setup_times_twct",
        hdrs = ["scheduling/parallel_scheduling_with_family_setup_times_twct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutation_flowshop_scheduling_makespan",
        hdrs = ["scheduling/permutation_flowshop_scheduling_makespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutation_flowshop_scheduling_tct",
        hdrs = ["scheduling/permutation_flowshop_scheduling_tct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "permutation_flowshop_scheduling_tt",
        hdrs = ["scheduling/permutation_flowshop_scheduling_tt.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "distributed_pfss_makespan",
        hdrs = ["scheduling/distributed_pfss_makespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "distributed_pfss_tct",
        hdrs = ["scheduling/distributed_pfss_tct.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "no_wait_job_shop_scheduling_makespan",
        hdrs = ["scheduling/no_wait_job_shop_scheduling_makespan.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
                "@interval-tree//:interval-tree",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "simple_assembly_line_balancing_1",
        hdrs = ["scheduling/simple_assembly_line_balancing_1.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_library(
        name = "u_shaped_assembly_line_balancing_1",
        hdrs = ["scheduling/u_shaped_assembly_line_balancing_1.hpp"],
        deps = [
                "@optimizationtools//optimizationtools/containers:containers",
                "@optimizationtools//optimizationtools/utils:utils",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "checker",
        srcs = ["checker.cpp"],
        deps = [
                ":knapsack_with_conflicts",
                ":multidimensional_multiple_choice_knapsack",
                ":cutting_stock",
                ":multiple_knapsack",
                ":quadratic_multiple_knapsack",
                ":generalized_quadratic_multiple_knapsack",
                ":bin_packing_with_conflicts",

                ":quadratic_assignment",

                ":traveling_salesman_with_release_dates",
                ":traveling_repairman",
                ":time_dependent_orienteering",
                ":orienteering_with_hotel_selection",
                ":capacitated_vehicle_routing",
                ":vehicle_routing_with_time_windows",
                ":capacitated_open_vehicle_routing",

                ":sequential_ordering",
                ":scheduling_with_sdst_twt",
                ":order_acceptance_and_scheduling",
                ":batch_scheduling_total_completion_time",
                ":batch_scheduling_total_weighted_tardiness",
                ":parallel_scheduling_with_family_setup_times_twct",
                ":permutation_flowshop_scheduling_makespan",
                ":permutation_flowshop_scheduling_tct",
                ":permutation_flowshop_scheduling_tt",
                ":distributed_pfss_makespan",
                ":distributed_pfss_tct",
                ":no_wait_job_shop_scheduling_makespan",
                ":simple_assembly_line_balancing_1",
                ":u_shaped_assembly_line_balancing_1",

                "@boost//:program_options",
        ],
        copts = ["-std=c++14"],
        linkopts = ["-std=c++14"],
)

